### ISSUE TITLE
SNES Emulation Addition

### ISSUE THREAD

**Issue by Revolution641** [nenge123/retroarch-web#3]
Can you possibly add Super Nintendo Entertainment System compatibility? I was able to myself but had to delete my fork of it.

**Comment by nenge123** [comment]
In fact, you can start each kernel separately when you can understand my function.

My warehouse is just showing how to perfectly start retroarch


If you like the web version very much, I suggest you go to my other warehouse to explore.

nenge123/emulatorjs 

download v4.99.19 replace! open F12 console.log test

**Comment by nenge123** [comment]
skyemu/skemu a best gb/gba emulator

**Comment by Revolution641** [comment]
Also, when I forked it again, and activated the github page, it won't show anything other than comments.

**Comment by nenge123** [comment]
> Also, when I forked it again, and activated the github page, it won't show anything other than comments.

you may change start.js 

T.version = 


# html

change js path "?xxxxx"


I hope you try not to foker agin. Try to modify your own version by yourself! If you have any problems to solve, you can issue here!thanks!

**Comment by nenge123** [comment]
snes added in config
